name: Initialize Dependencies Cache

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  init-cache:
    runs-on: ubuntu-20.04
    steps:
      - name: Create depends directories
        run: mkdir -p depends

      - name: Download pre-built depends
        run: |
          wget http://46.250.238.190:8080/depends.zip
          unzip depends.zip
          
      - name: List contents to verify
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of depends directory:"
          ls -la depends/

      - name: Save to cache
        uses: actions/cache/save@v3
        with:
          path: |
            depends/built
            depends/sources
            depends/work
            depends/x86_64-linux-gnu
          key: ${{ runner.os }}-depends-${{ github.sha }}

      - name: Output cache key
        run: |
          echo "Cache has been initialized with key: ${{ runner.os }}-depends-${{ github.sha }}"
          echo "Please update your main workflow to use this key"