name: Initialize Dependencies Cache

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  restore-cache-find-qt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore depends cache
        id: cache-depends
        uses: actions/cache/restore@v3
        with:
          path: |
            depends/built
            depends/sources
            depends/work
            depends/x86_64-linux-gnu
          key: linux-depends-2a7404608d0a5e86221b3255a866cc033cfd528e0e8ba683f5f3fb3933808a92

      - name: Check if cache was restored
        run: |
          if [ -z "${{ steps.cache-depends.outputs.cache-hit }}" ]; then
            echo "Cache not found. Exiting."
            exit 1
          fi

      - name: Unzip cache contents
        run: |
          mkdir -p depends-unzipped
          unzip -o depends/built/* -d depends-unzipped || echo "No zip file to unzip."

      - name: Find and grep Qt
        run: |
          find depends-unzipped | grep qt
