name: Build and Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update apt repositories
        run: sudo apt-get update

      - name: Install essential tools
        run: |
          sudo apt-get install -y \
          build-essential \
          xutils-dev \
          libicu-dev \
          libtool \
          gperf \
          autotools-dev \
          automake \
          pkg-config \
          bsdmainutils \
          libattr1-dev \
          make \
          bison \
          byacc \
          cmake \
          curl \
          g++-multilib \
          binutils-gold \
          python2 \
          coreutils

      - name: Set Python 2 as default
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
          sudo update-alternatives --set python /usr/bin/python2

      - name: Verify Python Version
        run: python --version  # Should print Python 2.7.x

      - name: Download latest LevelDB
        run: wget https://github.com/google/leveldb/archive/refs/tags/1.23.tar.gz -O leveldb.tar.gz

      - name: Extract LevelDB
        run: tar xvf leveldb.tar.gz

      - name: Build LevelDB
        run: |
          cd leveldb
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

      - name: Build dependencies
        run: cd depends && make -j4 HOST=x86_64-linux-gnu

      - name: Create database directories
        run: |
          mkdir -p db-4.8.30.NC/build_unix

      - name: Copy database static library
        run: cp /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/libdb_cxx.a /home/runner/work/tokenpay/tokenpay/db-4.8.30.NC/build_unix/
        
      - name: list made depends
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/ && ls -l
        
      - name: list made depends share
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/share && ls -l
        
      - name: list made depends share pkgconfig
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/share/pkgconfig && ls -l
        
      - name: list made depends include
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include && ls -l
        
      - name: list made depends include QtWebKit
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include/QtWebKit && ls -l
        
      - name: list made depends include QtCore
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include/QtCore && ls -l
        
      - name: list made depends include boost
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include/boost && ls -l

      - name: list made depends lib pkgconfig
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig && ls -l
        
      - name: list made depends bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/bin && ls -l
        
      - name: list made depends native
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native && ls -l
        
      - name: list made depends native bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native/bin && ls -l

      - name: List built dependencies
        run: ls -l /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib

      - name: Add paths to environment
        run: |
          echo "LIBRARY_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib:\$LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "CXXFLAGS=-I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include \$CXXFLAGS" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include \$CPPFLAGS" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig:\$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Add binary paths to PATH
        run: echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native/bin" >> $GITHUB_PATH

      - name: Verify environment variables
        run: |
          echo "LIBRARY_PATH: $LIBRARY_PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "CXXFLAGS: $CXXFLAGS"
          echo "CPPFLAGS: $CPPFLAGS"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"

      - name: Verify pkg-config
        run: |
          pkg-config --libs Qt5WebKit
          pkg-config --libs Qt5WebKitWidgets

      - name: Run autogen script
        run: ./autogen.sh

      - name: Configure project
        env:
          PKG_CONFIG_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig
          LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          LD_LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          CXXFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
          CPPFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
        run: |
          CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site \
          ./configure \
          --enable-gui \
          --disable-bench \
          --disable-tests \
          --disable-dependency-tracking \
          --disable-werror \
          --prefix=`pwd`/depends/x86_64-linux-gnu \
          --bindir=`pwd`/release/bin \
          --libdir=`pwd`/release/lib

      - name: Compile project
        env:
          PKG_CONFIG_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig
          LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          LD_LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          CXXFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
          CPPFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
        run: make
