on:
  push

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install essential tools
        run: |
          sudo apt-get install -y \
          build-essential \
          xutils-dev \
          libicu-dev \
          libtool \
          gperf \
          autotools-dev \
          automake \
          pkg-config \
          bsdmainutils \
          libattr1-dev \
          make \
          bison \
          byacc \
          cmake \
          curl \
          g++-multilib \
          binutils-gold \
          python2 \
          coreutils

      - name: Set Python 2 as default
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
          sudo update-alternatives --set python /usr/bin/python2

      - name: Verify Python Version
        run: python --version  # Should print Python 2.7.x

      - name: Build dependencies
        run: cd depends/ && make -j4 HOST=x86_64-linux-gnu

      - name: Add paths to environment
        run: |
          echo "LIBRARY_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib:\$LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "CXXFLAGS=-I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include \$CXXFLAGS" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include \$CPPFLAGS" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig:\$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Add binary paths to PATH
        run: echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native/bin" >> $GITHUB_PATH

      - name: Verify environment variables
        run: |
          echo "LIBRARY_PATH: $LIBRARY_PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "CXXFLAGS: $CXXFLAGS"
          echo "CPPFLAGS: $CPPFLAGS"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"

      - name: Verify files in lib directory
        run: ls -l /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib

      - name: Verify include files
        run: ls -l /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include

      - name: Verify pkg-config files
        run: ls -l /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure project
        env:
          PKG_CONFIG_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig
          LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          LD_LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          CXXFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
          CPPFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
        run: |
          CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site \
          ./configure \
          --enable-gui \
          --disable-bench \
          --disable-tests \
          --disable-dependency-tracking \
          --disable-werror \
          --prefix=`pwd`/depends/x86_64-linux-gnu \
          --bindir=`pwd`/release/bin \
          --libdir=`pwd`/release/lib

      - name: Compile project
        env:
          PKG_CONFIG_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig
          LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          LD_LIBRARY_PATH: /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib
          CXXFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
          CPPFLAGS: -I/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include
        run: make
