on:
  push

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install build-essential xutils-dev libicu-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold bison byacc python2

      - name: Set Python 2 as default
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
          sudo update-alternatives --set python /usr/bin/python2

      - name: Verify Python Version
        run: python --version  # Should print Python 2.7.x

      - name: Build depends
        run: cd depends/ && make -j4 HOST=x86_64-linux-gnu
        
      - name: find qmake
        run: sudo find / -name qmake 2>/dev/null
        
      - name: list usr/bin
        run: cd /usr/bin && ls
        
      - name: list usr/local/bin
        run: cd /usr/local/bin && ls
        
      - name: list usr/local
        run: cd /usr/local/ && ls
      
      - name: list made depends
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/ && ls
        
      - name: list made depends share
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/share && ls
        
      - name: list made depends share pkgconfig
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/share/pkgconfig && ls
        
      - name: list made depends include
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include && ls
        
      - name: list made depends include boost
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/include/boost && ls
        
      - name: list made depends lib
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib && ls
        
      - name: list made depends lib pkgconfig
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig && ls
        
      - name: list made depends bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/bin && ls
        
      - name: list made depends native
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native && ls
        
      - name: list made depends native bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native/bin && ls

      - name: Add uic path to environment
        run: echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native/bin" >> $GITHUB_PATH
        
      - name: add pkgconfig lib to path
        run: echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig" >> $GITHUB_PATH

      - name: Verify uic path
        run: which uic
        
      - name: mk db dir and subdir
        run: mkdir db-4.8.30.NC && cd db-4.8.30.NC && mkdir build_unix
      
      - name: go in and copy db .a to needed location
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib && cp libdb_cxx.a /home/runner/work/tokenpay/tokenpay/db-4.8.30.NC/build_unix/

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --enable-gui --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib
        
      - name: make
        run: make

