on:
  push

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install build-essential xutils-dev libicu-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold bison byacc python2

      - name: Set Python 2 as default
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
          sudo update-alternatives --set python /usr/bin/python2

      - name: Verify Python Version
        run: python --version  # Should print Python 2.7.x

      - name: Build depends
        run: cd depends/ && make -j4 HOST=x86_64-linux-gnu
        
      - name: Add library path to environment
        run: |
          echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib" >> $GITHUB_ENV
          echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib" >> $GITHUB_PATH
          echo "export LIBRARY_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib:\$LIBRARY_PATH" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Verify library path
        run: |
          echo $LIBRARY_PATH
          echo $LD_LIBRARY_PATH

      - name: find qmake
        run: sudo find / -name qmake 2>/dev/null
        
      - name: list usr/bin
        run: cd /usr/bin && ls
        
      - name: list usr/local/bin
        run: cd /usr/local/bin && ls
        
      - name: list usr/local
        run: cd /usr/local/ && ls
     
      - name: Add pkg-config path
        run: echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/pkgconfig" >> $PKG_CONFIG_PATH
        
      - name: list made depends lib
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib && ls
        
      - name: Add uic path to environment
        run: echo "/home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/native/bin" >> $GITHUB_PATH
        
      - name: Verify uic path
        run: which uic
        
      - name: mk db dir and subdir
        run: mkdir db-4.8.30.NC && cd db-4.8.30.NC && mkdir build_unix
      
      - name: Copy db .a to needed location
        run: cp /home/runner/work/tokenpay/tokenpay/depends/x86_64-linux-gnu/lib/libdb_cxx.a /home/runner/work/tokenpay/tokenpay/db-4.8.30.NC/build_unix/

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure project
        run: CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --enable-gui --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib
        
      - name: Compile project
        run: make
