on: 
  push:
    branches:
      - main  # or your target branch

jobs:
  windows32-ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install base tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool automake pkg-config bsdmainutils curl git

      - name: Set up MingW32 Cross Compile tools
        run: |
          sudo apt-get install -y g++-mingw-w64-i686 mingw-w64-i686-dev
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix

      - name: Build dependencies in the depends folder
        run: |
          PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
          cd depends/
          make HOST=i686-w64-mingw32
          
      - name: get and untar bdb4.8
        run: wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz && tar -xzvf db-4.8.30.NC.tar.gz
        
      - name: list files
        run: ls
        
      - name: fix atomic
        run: cd db-4.8.30.NC/build_unix/ && sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' /home/runner/work/tokenpay-linux/tokenpay-linux/db-4.8.30.NC/dbinc/atomic.h 
        
      - name: build bdb4.8
        run: cd db-4.8.30.NC/build_unix/ && ../dist/configure --disable-replication --enable-mingw --enable-cxx --prefix=/mingw
        
      - name: make and make install 
        run: cd db-4.8.30.NC/build_unix/ && make && sudo make install
          
      - name: list usr/bin
        run: cd /usr/bin && ls
        
      - name: list usr/local/bin
        run: cd /usr/local/bin && ls
        
      - name: list usr/local
        run: cd /usr/local/ && ls
      
      - name: list made depends
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/ && ls
        
      - name: list made depends include
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/include && ls
        
      - name: list made depends lib
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/lib && ls
        
      - name: list made depends lib pkgconfig
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/lib/pkgconfig && ls
        
      - name: list made depends bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/bin && ls
        
      - name: list made depends native
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/native && ls
        
      - name: list made depends native bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/i686-w64-mingw32/native/bin && ls

      - name: Auto-generate configuration
        run: ./autogen.sh

  windows64-ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install base tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool automake pkg-config bsdmainutils curl git

      - name: Set up MingW64 Cross Compile tools
        run: |
          sudo apt-get install -y g++-mingw-w64-x86-64
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 

      - name: Build dependencies in the depends folder
        run: |
          PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
          cd depends/
          make HOST=x86_64-w64-mingw32
          
      - name: get and untar bdb4.8
        run: wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz && tar -xzvf db-4.8.30.NC.tar.gz
        
      - name: list files
        run: ls
        
      - name: fix atomic
        run: cd db-4.8.30.NC/build_unix/ && sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' /home/runner/work/tokenpay-linux/tokenpay-linux/db-4.8.30.NC/dbinc/atomic.h 
        
      - name: build bdb4.8
        run: cd db-4.8.30.NC/build_unix/ && ../dist/configure --disable-replication --enable-mingw --enable-cxx --prefix=/mingw
        
      - name: make and make install 
        run: cd db-4.8.30.NC/build_unix/ && make && sudo make install
          
      - name: list usr/bin
        run: cd /usr/bin && ls
        
      - name: list usr/local/bin
        run: cd /usr/local/bin && ls
        
      - name: list usr/local
        run: cd /usr/local/ && ls
          
      - name: list made depends
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/ && ls
        
      - name: list made depends include
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/include && ls
        
      - name: list made depends lib
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/lib && ls
        
      - name: list made depends lib pkgconfig
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/lib/pkgconfig && ls
        
      - name: list made depends bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/bin && ls
        
      - name: list made depends native
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/native && ls
        
      - name: list made depends native bin
        run: cd /home/runner/work/tokenpay/tokenpay/depends/x86_64-w64-mingw32/native/bin && ls

      - name: Auto-generate configuration
        run: ./autogen.sh



